
services:
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch-node1
    environment:
      - node.name=elasticsearch-node1
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch-node2
      - cluster.initial_master_nodes=elasticsearch-node1,elasticsearch-node2
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization,x-elastic-client-meta
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  
  elasticsearch-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch-node2
    environment:
      - node.name=elasticsearch-node2
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch-node1
      - cluster.initial_master_nodes=elasticsearch-node1,elasticsearch-node2
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*""
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    ports:
      - "9201:9200"
    volumes:
      - esdata2:/usr/share/elasticsearch/data

  cv-indexing:
    build:
      context: ./elastic-backend
      dockerfile: Dockerfile
    container_name: cv-indexing
    depends_on:
      elasticsearch-node1:
        condition: service_healthy
      elasticsearch-node2:
        condition: service_healthy
    environment:
      - ELASTIC_ENDPOINT=http://elasticsearch-node1:9200
    command: ["python", "elastic-backend/cv-index.py"]

  search-ui:
    build: 
      context: ../search-ui
      dockerfile: Dockerfile
    container_name: search-ui
    environment:
      # for local dev
      # - REACT_APP_ELASTIC_ENDPOINT=http://localhost:9200
      # for AWS deployment:
      - REACT_APP_ELASTIC_ENDPOINT=http://elasticsearch-node1:9200
      - REACT_APP_INDEX_NAME=cv-transcriptions
      # Include the API key if security is enabled
      - REACT_APP_ELASTIC_API_KEY=u99O8CffTxeTQX-K7lTwAg # search only key
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch-node1

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - search-ui

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
