
services:
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch-node1
    environment:
      - node.name=elasticsearch-node1
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch-node2
      - cluster.initial_master_nodes=elasticsearch-node1,elasticsearch-node2
      # - ELASTIC_PASSWORD=elastic4asr
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization,x-elastic-client-meta
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      # - ../data/common_voice/cv-valid-dev.csv:/usr/share/elasticsearch/cv-valid-dev.csv:ro
  
  elasticsearch-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch-node2
    environment:
      - node.name=elasticsearch-node2
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch-node1
      - cluster.initial_master_nodes=elasticsearch-node1,elasticsearch-node2
      # - ELASTIC_PASSWORD=elastic4asr
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*""
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    ports:
      - "9201:9200"
    volumes:
      - esdata2:/usr/share/elasticsearch/data

  search-ui:
    build: ../search-ui
    container_name: search-ui
    environment:
      # Point to the Elasticsearch service; note that inside Docker, use the service name
      - REACT_APP_ELASTIC_ENDPOINT=http://localhost:9200
      - REACT_APP_INDEX_NAME=cv-transcriptions
      # Include the API key if security is enabled (or remove if not needed)
      - REACT_APP_ELASTIC_API_KEY=u99O8CffTxeTQX-K7lTwAg # search only key
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch-node1

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
